parameters:
#    digitalshift_mailbox_persistence.example.class: Digitalshift\MailboxPersistenceBundle\Example

services:
#    digitalshift_mailbox_persistence.example:
#        class: %digitalshift_mailbox_persistence.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
