parameters:
    digitalshift_mailbox_persistence.attachment_persister.class: Digitalshift\MailboxPersistenceBundle\Persistence\Attachment\FilesystemAttachmentPersister

services:
    digitalshift_mailbox_persistence.attachment_persister:
        class: %digitalshift_mailbox_persistence.attachment_persister.class%
        arguments: ["%kernel.root_dir%/../web", "tmp"]
